import { MAX_RUBRIC_SCORE, RUBRIC_LABELS } from '@shared/constants.js';
import type { RubricEntry } from '@shared/types.js';
import { formatTimestamp } from '../lib/format.js';

interface Props {
  rubric: RubricEntry[];
  onSeek: (seconds: number) => void;
}

function scoreTone(score: number): string {
  if (score >= 4) return 'bg-signal-low';
  if (score >= 3) return 'bg-signal-medium';
  return 'bg-signal-high';
}

export default function RubricPanel({ rubric, onSeek }: Props) {
  if (rubric.length === 0) return null;

  return (
    <section aria-labelledby="rubric-heading">
      <h2
        id="rubric-heading"
        className="font-display text-sm tracking-wide text-ink-soft uppercase"
      >
        Evaluation rubric
      </h2>
      <p className="mt-1 mb-4 text-sm text-ink-muted">
        Six dimensions, each scored 0 to {MAX_RUBRIC_SCORE} against what is actually present in the
        video. The readiness heuristic is computed from these scores, not generated by the model.
      </p>

      <div className="divide-y divide-line border border-line bg-paper-raised">
        {rubric.map((entry) => (
          <div key={entry.dimension} className="p-4 sm:p-5">
            <div className="flex items-baseline justify-between gap-4">
              <h3 className="font-medium">{RUBRIC_LABELS[entry.dimension]}</h3>
              <span className="shrink-0 text-sm tabular-nums text-ink-muted">
                <span className="font-display text-lg text-ink">{entry.score}</span>
                {' / '}
                {MAX_RUBRIC_SCORE}
              </span>
            </div>

            <div
              className="mt-2 flex gap-1"
              role="img"
              aria-label={`${entry.score} out of ${MAX_RUBRIC_SCORE}`}
            >
              {Array.from({ length: MAX_RUBRIC_SCORE }, (_, i) => (
                <span
                  key={i}
                  className={`h-1 flex-1 rounded-full ${
                    i < entry.score ? scoreTone(entry.score) : 'bg-line'
                  }`}
                />
              ))}
            </div>

            <p className="mt-3 text-sm leading-relaxed text-ink-soft">{entry.summary}</p>

            {entry.evidenceTimestamps.length > 0 && (
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <span className="text-xs text-ink-muted">Evidence:</span>
                {entry.evidenceTimestamps.map((ts) => (
                  <button
                    key={ts}
                    type="button"
                    onClick={() => onSeek(ts)}
                    className="rounded-sm border border-line px-1.5 py-0.5 text-xs tabular-nums text-ink-soft transition-colors hover:border-ink hover:text-ink"
                    aria-label={`Jump to ${formatTimestamp(ts)}`}
                  >
                    {formatTimestamp(ts)}
                  </button>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}
